### ISSUE TITLE
Chapter Bike algorithms

### ISSUE THREAD

**Issue by nateraluis** [nateraluis/PhD-thesis#9]
## TODO:

- [x] Split figure algorithms improvements
- [x] Split figure 5 km and 10 km
- [x] Check references to figures
- [ ] Write some introduction
